### PR TITLE
Support django1.9

### PR DESCRIPTION
**Pull request by siulpolb**
I just change the version of some packages to support Django 1.9.
Also delete files that were no longer in use.

### CODE REVIEW

**Comment by lyanaz** [comment]
Does simply changing the requirement from Django 1.6 to Django 1.9 help? I've tried but It does not seem to work

**Comment by fe01134** [comment]
Hi Guys, I will try and test this pull request to see if it works this weekend. If it does I will merge it back in to the original.  I have been meaning to update to the latest django version so this gave me the incentive to do it.  Thanks.

**Comment by siulpolb** [comment]
Hi.
Only change the requirement from 1.6 to 1.9 doesn't work, you need to upgrade to the most recent version of dj-static and dj-database-url and change the syncdb command for makemigration and migrate in run.sh, this because syncdb is deprecated on django 1.9.

I test the chages myself, I hope this work fine with you too.

**Comment by lyanaz** [comment]
Hi Guys, 

Thanks. Changing all the requirements as in your requirement worked. It helped a lot.

**Pull request merged**
